name: application
on:
  push:
    branches:
      - main
    paths:
    - 'src/**'
    - '.github/workflows/app.yml'
  workflow_dispatch:

env:
  FUNCTION_APP_NAME: smoldata-fa
  FUNCTION_APP_PACKAGE_PATH: '/src/Smoldata.Api'
  RESOURCE_GROUP_NAME: smoldata-rg
  DOTNET_VERSION: '6.0.x'

jobs:
  Application:
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main
    - name: 'Login via Azure CLI'
      uses: azure/login@v1.4.4
      with:
        creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}
    - name: Setup .NET ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: 'Resolve Project Dependencies'
      shell: bash
      run: |
        pushd './${{ env.FUNCTION_APP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1.4.7
      id: fa
      with:
        app-name: ${{ env.FUNCTION_APP_NAME }}
        package: './${{ env.FUNCTION_APP_PACKAGE_PATH }}/output'